CREATE TRIGGER TR_UpdateClientes ON Clientes
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE Clientes
    SET UpdatedAt = GETDATE()
    WHERE Id IN (SELECT Id FROM INSERTED);
END;
GO

CREATE TRIGGER TR_DeleteClientes ON Clientes
INSTEAD OF DELETE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE Clientes
    SET DeletedAt = GETDATE()
    WHERE Id IN (SELECT Id FROM DELETED);
END;
GO