CREATE TRIGGER TR_UpdateCanchas ON Canchas
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE Canchas
    SET UpdatedAt = GETDATE()
    WHERE Id IN (SELECT Id FROM INSERTED);
END;
GO

CREATE TRIGGER TR_DeleteCanchas ON Canchas
INSTEAD OF DELETE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE Canchas
    SET DeletedAt = GETDATE()
    WHERE Id IN (SELECT Id FROM DELETED);
END;
GO