CREATE TRIGGER TR_UpdateMetodoPago ON MetodoPago
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE MetodoPago
    SET UpdatedAt = GETDATE()
    WHERE Id IN (SELECT Id FROM INSERTED);
END;
GO

CREATE TRIGGER TR_DeleteMetodoPago ON MetodoPago
INSTEAD OF DELETE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE MetodoPago
    SET DeletedAt = GETDATE()
    WHERE Id IN (SELECT Id FROM DELETED);
END;
GO
