CREATE TRIGGER TR_UpdatePrecios ON Precios
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE Precios
    SET UpdatedAt = GETDATE()
    WHERE Id IN (SELECT Id FROM INSERTED);
END;
GO

CREATE TRIGGER TR_DeletePrecios ON Precios
INSTEAD OF DELETE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE Precios
    SET DeletedAt = GETDATE()
    WHERE Id IN (SELECT Id FROM DELETED);
END;
GO