CREATE TRIGGER TR_UpdatePagos ON Pagos
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE Pagos
    SET UpdatedAt = GETDATE()
    WHERE Id IN (SELECT Id FROM INSERTED);
END;
GO

CREATE TRIGGER TR_DeletePagos ON Pagos
INSTEAD OF DELETE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE Pagos
    SET DeletedAt = GETDATE()
    WHERE Id IN (SELECT Id FROM DELETED);
END;
GO