CREATE TRIGGER TR_UpdateTipoCancha ON TipoCancha
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE TipoCancha
    SET UpdatedAt = GETDATE()
    WHERE Id IN (SELECT Id FROM INSERTED);
END;
GO

CREATE TRIGGER TR_DeleteTipoCancha ON TipoCancha
INSTEAD OF DELETE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE TipoCancha
    SET DeletedAt = GETDATE()
    WHERE Id IN (SELECT Id FROM DELETED);
END;
GO